server.port=8080

# Spring Data JPA & SQLite Database Configuration
spring.datasource.url=jdbc:sqlite:policycenter.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

# Enable DevTools LiveReload
spring.devtools.livereload.enabled=true
spring.devtools.restart.enabled=true

# Static Web Assets (Frontend)
spring.web.resources.static-locations=file:frontend/
